import { useState, useRef, useEffect } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import './App.css'

interface Message {
  id: string;
  sender: 'user' | 'agent' | 'status';
  text: string;
  timestamp: string;
  phases?: { name: string; status: 'pending' | 'active' | 'completed' }[];
}

const SAMPLE_BRIEF = `# COUNSELCORE: PRELIMINARY LEGAL STRATEGY BRIEF
**CONFIDENTIAL // ATTORNEY-CLIENT PRIVILEGE**

---

## 1. EXECUTIVE SUMMARY & ENGAGEMENT METRICS
* **Matter Category:** Employment Law / Restrictive Covenants
* **Generated By:** CounselCore Autonomous Legal Research Agent
* **Platform:** AWS Bedrock (Claude Engine) & Strands Agents SDK
* **Status:** Draft (For Internal Attorney Review Only)

### Brief Summary
This strategy document has been autonomously compiled by parsing client case notes, querying our curated legal databases for statutory framework and judicial precedents, and synthesizing the findings. The primary objective is to evaluate potential liabilities, outline defenses, and formulate a step-by-step litigation or compliance strategy.

---

## 2. STATEMENT OF CLIENT FACTS
Below is the factual background provided for evaluation:

> Employee is being sued in California for violating a nationwide non-compete clause in their employment contract after joining a competitor.

---

## 3. STATUTORY FRAMEWORK & LEGISLATIVE AUTHORITY
The following statutory sections have been identified as highly relevant to this matter:

### 1. California Business and Professions Code - Void Contracts
* **Citation:** \`Cal. Bus. & Prof. Code § 16600\`
* **Jurisdiction:** California, USA
* **Overview:** Except as provided in this chapter, every contract by which anyone is restrained from engaging in a lawful profession, trade, or business of any kind is to that extent void.
* **Key Provisions:**
    * Voiding of restrictive covenants: Declares non-compete agreements in employment context strictly invalid.
    * Exceptions: Limited to sale of business goodwill, partnership dissolution, or LLC member dissociation.

---

## 4. JUDICIAL PRECEDENTS & CASE LAW ANALYSIS
The following binding or persuasive judicial precedents provide guidance on how courts interpret these issues:

### 1. NovaTech Solutions v. Apex Systems Corp.
* **Citation:** *842 F.3d 1105 (9th Cir. 2023)* (United States Court of Appeals for the Ninth Circuit, 2023)
* **Jurisdiction:** California / Federal / 9th Circuit
* **Factual Matrix:** An employer sought to enforce a nationwide non-compete clause against a former software architect. The agreement barred employment with any tech company for three years.
* **Holding:** The non-compete clause was found to be overly broad and geographically unreasonable, making it completely unenforceable under California Business and Professions Code Section 16600.
* **Core Legal Principle:** Restrictive covenants in employment agreements must have a reasonable geographical scope, a limited duration, and protect a clear legitimate interest (such as trade secrets). In California, non-compete agreements are void ab initio except in extremely narrow statutory exceptions.

---

## 5. STRATEGIC ANALYSIS & LEGAL ASSESSMENT

### Strengths of the Client's Position
* **Statutory Compliance / Protections:** If applicable, state statutes provide strong consumer or employee protections which may invalidate the opposition's claims or strengthen the client's cause of action.
* **Precedential Support:** Key holdings in precedent cases align closely with the core facts here (e.g., requirements of reasonableness, standard of care, or fair use criteria).
* **Factual Merits:** The client's actions demonstrate a reasonable, good-faith attempt to comply with standard procedures or laws.

### Weaknesses & Potential Vulnerabilities
* **Geographical and Jurisdictional Ambiguities:** Differences in state-level enforcement (e.g., California vs. Texas on non-competes) create significant venue risks.
* **Factual Distinctions:** The opposition may attempt to distinguish precedent cases by highlighting differences in commercial impact or professional relationships.
* **Evidentiary Gaps:** Success may heavily depend on establishing specific proof, such as demonstrating exact "transformative use," proving standard of care deviations, or documenting reasonable security measures.

---

## 6. RECOMMENDED ACTION PLAN & NEXT STEPS
1. **Jurisdictional Selection (Venue):** Carefully choose the filing venue or respond in a venue that maximizes favorable law (e.g., seeking California jurisdiction for non-compete matters).
2. **Document Preservation & Discovery:** Issue immediate litigation hold letters and preserve all relevant communications, contracts, protocols, or logs.
3. **Drafting Pleadings:** Utilize the statutory and precedential arguments outlined in Sections 3 and 4 as the foundation for the Answer, Motion to Dismiss, or Complaint.
4. **Expert Witness Engagement:** In professional negligence or data breach cases, identify potential expert witnesses to establish standard of care or industry standards.

---
*Disclaimer: CounselCore is an AI legal research agent powered by AWS Bedrock and the Strands Agents SDK. This document is a preliminary work product intended to assist licensed legal professionals. It does not constitute formal, binding legal advice.*
`;

function App() {
  const [inputText, setInputText] = useState('');
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'welcome',
      sender: 'agent',
      text: "Welcome to CounselCore. I am your autonomous legal co-pilot. Input your case notes, client interview facts, or legal dispute details below, and I will search statutes, consult precedents, and draft a structured Legal Strategy Brief for you.",
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    }
  ]);
  const [currentBrief, setCurrentBrief] = useState<string>('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [backendMode, setBackendMode] = useState<'live' | 'mock'>('live');
  const [backendStatus, setBackendStatus] = useState<'unknown' | 'connected' | 'disconnected'>('unknown');
  
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll chat to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Check backend server connection
  useEffect(() => {
    const checkConnection = async () => {
      try {
        const res = await fetch('http://127.0.0.1:8000/api/health', { method: 'GET' });
        if (res.ok) {
          setBackendStatus('connected');
          setBackendMode('live');
        } else {
          setBackendStatus('disconnected');
          setBackendMode('mock');
        }
      } catch {
        setBackendStatus('disconnected');
        setBackendMode('mock');
      }
    };
    checkConnection();
  }, []);

  const handleSend = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputText.trim() || isProcessing) return;

    const userText = inputText.trim();
    setInputText('');

    // Add user message
    const userMsgId = Math.random().toString(36).substring(7);
    const userMsg: Message = {
      id: userMsgId,
      sender: 'user',
      text: userText,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };
    setMessages((prev) => [...prev, userMsg]);
    setIsProcessing(true);

    // Add status/pipeline tracker message
    const statusMsgId = Math.random().toString(36).substring(7);
    const initialPhases = [
      { name: 'Phase 1/4: Analyzing factual matrix and isolating themes...', status: 'active' as const },
      { name: 'Phase 2/4: Querying statutory database for regulatory authority...', status: 'pending' as const },
      { name: 'Phase 3/4: Retrieving judicial precedents and holdings...', status: 'pending' as const },
      { name: 'Phase 4/4: Triggering Bedrock reasoning & compiling brief...', status: 'pending' as const },
    ];
    
    setMessages((prev) => [
      ...prev,
      {
        id: statusMsgId,
        sender: 'status',
        text: 'Launching CounselCore Autonomous Pipeline...',
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        phases: initialPhases
      }
    ]);

    if (backendMode === 'mock') {
      // --- SIMULATED MOCK RUN ---
      // Cycle through phases with timeouts
      for (let i = 0; i < 4; i++) {
        await new Promise((resolve) => setTimeout(resolve, i === 0 ? 1200 : i === 1 ? 1400 : 1600));
        setMessages((prev) =>
          prev.map((msg) => {
            if (msg.id === statusMsgId && msg.phases) {
              const updatedPhases = [...msg.phases];
              updatedPhases[i].status = 'completed';
              if (i < 3) {
                updatedPhases[i + 1].status = 'active';
              }
              return { ...msg, phases: updatedPhases };
            }
            return msg;
          })
        );
      }

      // Deliver final mock brief
      setCurrentBrief(SAMPLE_BRIEF);
      setMessages((prev) => [
        ...prev,
        {
          id: Math.random().toString(36).substring(7),
          sender: 'agent',
          text: 'Strategy compilation complete! The generated Legal Strategy Brief is now ready on your right panel.',
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        }
      ]);
      setIsProcessing(false);
    } else {
      // --- LIVE BACKEND RUN ---
      try {
        // Stream / Fetch from live FastAPI python backend
        const updateStatusPhase = (phaseIndex: number) => {
          setMessages((prev) =>
            prev.map((msg) => {
              if (msg.id === statusMsgId && msg.phases) {
                const updatedPhases = [...msg.phases];
                updatedPhases[phaseIndex].status = 'completed';
                if (phaseIndex < 3) {
                  updatedPhases[phaseIndex + 1].status = 'active';
                }
                return { ...msg, phases: updatedPhases };
              }
              return msg;
            })
          );
        };

        // Simulate phase transitions leading up to the API call
        setTimeout(() => updateStatusPhase(0), 1000);
        setTimeout(() => updateStatusPhase(1), 2200);
        setTimeout(() => updateStatusPhase(2), 3400);

        const response = await fetch('http://127.0.0.1:8000/api/research', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ facts: userText })
        });

        if (!response.ok) {
          throw new Error('API server returned error status');
        }

        const data = await response.json();
        
        // Finalize all phases
        setMessages((prev) =>
          prev.map((msg) => {
            if (msg.id === statusMsgId && msg.phases) {
              return {
                ...msg,
                phases: msg.phases.map(p => ({ ...p, status: 'completed' }))
              };
            }
            return msg;
          })
        );

        setCurrentBrief(data.brief);
        setMessages((prev) => [
          ...prev,
          {
            id: Math.random().toString(36).substring(7),
            sender: 'agent',
            text: 'I have compiled the legal research and assembled a custom Legal Strategy Brief. You can review and download the markdown document on the right pane.',
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
          }
        ]);
      } catch (error: any) {
        console.error(error);
        setMessages((prev) => [
          ...prev,
          {
            id: Math.random().toString(36).substring(7),
            sender: 'agent',
            text: `❌ Error connecting to live agent server: ${error.message || 'Server offline'}. Switching to Mock mode for evaluation.`,
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
          }
        ]);
        setBackendMode('mock');
        // Let them run again in mock mode
      } finally {
        setIsProcessing(false);
      }
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(currentBrief);
    alert('Brief copied to clipboard!');
  };

  const handleDownload = () => {
    const blob = new Blob([currentBrief], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'CounselCore_Legal_Strategy_Brief.md';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="app-container">
      {/* Global Header Banner */}
      <header className="main-header">
        <div className="logo-container">
          <div className="logo-icon">⚖</div>
          <div className="logo-text">
            <h1>CounselCore</h1>
            <p>Autonomous Legal Research Agent</p>
          </div>
        </div>
        
        <div className="header-meta">
          <span className="badge track">Professional Agents</span>
          <span className="badge sdk">Strands SDK</span>
          
          <div className="connection-selector">
            <span className={`status-indicator ${backendStatus}`}></span>
            <select 
              value={backendMode} 
              onChange={(e) => setBackendMode(e.target.value as 'live' | 'mock')}
            >
              <option value="live">Live Backend {backendStatus === 'connected' ? '✓' : ''}</option>
              <option value="mock">Simulated (Local Mock)</option>
            </select>
          </div>
        </div>
      </header>

      {/* Main Split Interface */}
      <main className="main-layout">
        {/* Left Pane - Chat panel */}
        <section className="chat-panel">
          <div className="panel-title-bar">
            <h2>Research Console</h2>
            <span className="subtitle">Case intake & analysis pipeline</span>
          </div>

          <div className="messages-container">
            {messages.map((msg) => (
              <div key={msg.id} className={`message-wrapper ${msg.sender}`}>
                {msg.sender === 'agent' && <div className="message-avatar">⚖</div>}
                
                <div className={`message-bubble ${msg.sender}`}>
                  {msg.sender === 'status' ? (
                    <div className="pipeline-tracker">
                      <div className="tracker-title">
                        <span className="pulse-dot"></span>
                        <strong>{msg.text}</strong>
                      </div>
                      <div className="pipeline-steps">
                        {msg.phases?.map((phase, idx) => (
                          <div key={idx} className={`pipeline-step ${phase.status}`}>
                            <span className="step-bullet">
                              {phase.status === 'completed' ? '✓' : phase.status === 'active' ? '●' : '○'}
                            </span>
                            <span className="step-name">{phase.name}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  ) : (
                    <p className="message-text">{msg.text}</p>
                  )}
                  <span className="message-time">{msg.timestamp}</span>
                </div>
                
                {msg.sender === 'user' && <div className="message-avatar user">U</div>}
              </div>
            ))}
            <div ref={messagesEndRef} />
          </div>

          {/* Input formulation area */}
          <form className="input-form" onSubmit={handleSend}>
            <textarea
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              placeholder="Paste facts or client intake notes here (e.g. 'An employee in California is being sued for violating a non-compete...')"
              disabled={isProcessing}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  handleSend(e);
                }
              }}
            />
            <button 
              type="submit" 
              className={`submit-btn ${isProcessing ? 'disabled' : ''}`}
              disabled={isProcessing || !inputText.trim()}
            >
              {isProcessing ? 'Processing Case...' : 'Analyze Case & Draft Brief'}
            </button>
          </form>
        </section>

        {/* Right Pane - Legal Brief Viewer */}
        <section className="brief-panel">
          <div className="panel-title-bar">
            <h2>Legal Strategy Brief</h2>
            
            {currentBrief && (
              <div className="brief-actions">
                <button className="brief-btn copy" onClick={handleCopy}>
                  Copy Markdown
                </button>
                <button className="brief-btn download" onClick={handleDownload}>
                  Download Document
                </button>
              </div>
            )}
          </div>

          <div className="brief-viewer-content">
            {currentBrief ? (
              <div className="brief-markdown-render">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                  {currentBrief}
                </ReactMarkdown>
              </div>
            ) : (
              <div className="brief-placeholder">
                <div className="placeholder-icon">📋</div>
                <h3>No Case Selected</h3>
                <p>
                  Provide a client intake story or case facts on the Left Intake panel and trigger the autonomous pipeline to compile a comprehensive, citation-rich Legal Strategy Brief here.
                </p>
                <div className="placeholder-suggestions">
                  <p className="suggest-title">Suggested Scenarios to try:</p>
                  <button 
                    onClick={() => setInputText("An employee in California is being sued for violation of a non-compete agreement.")}
                    className="suggest-btn"
                  >
                    California Non-Compete Breach
                  </button>
                  <button 
                    onClick={() => setInputText("Our company is accused of copyright infringement by an agency claiming our AI marketing assets copied their original designs. We believe it is fair use.")}
                    className="suggest-btn"
                  >
                    Generative AI Copyright Fair Use
                  </button>
                </div>
              </div>
            )}
          </div>
        </section>
      </main>
    </div>
  )
}

export default App
